-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 21:10:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinemar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinemar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinemar` DEFAULT CHARACTER SET utf8mb4 ;
USE `cinemar` ;

-- -----------------------------------------------------
-- Table `cinemar`.`tipo_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`tipo_sala` (
  `id_tipoSala` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoSala`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`sala` (
  `idSala` INT(11) NOT NULL AUTO_INCREMENT,
  `capacidad` INT(11) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idTiposala` INT(11) NOT NULL,
  PRIMARY KEY (`idSala`),
  INDEX `FK_sala_tiposala` (`idTiposala` ASC) VISIBLE,
  CONSTRAINT `FK_sala_tiposala`
    FOREIGN KEY (`idTiposala`)
    REFERENCES `cinemar`.`tipo_sala` (`id_tipoSala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`butacas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`butacas` (
  `idButacas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `idSala` INT(11) NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idButacas`),
  INDEX `FK_butacas_butacas` (`idSala` ASC) VISIBLE,
  CONSTRAINT `FK_butacas_butacas`
    FOREIGN KEY (`idSala`)
    REFERENCES `cinemar`.`sala` (`idSala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`genero` (
  `idGenero` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`peliculas` (
  `idPeliculas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `duracion` VARCHAR(50) NOT NULL,
  `atp` TINYINT(4) NOT NULL,
  `idGenero` INT(11) NOT NULL,
  `plus` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idPeliculas`),
  INDEX `FK_paliculas_genero` (`idGenero` ASC) VISIBLE,
  CONSTRAINT `FK_paliculas_genero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `cinemar`.`genero` (`idGenero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`cartelera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`cartelera` (
  `idCartelera` INT(11) NOT NULL AUTO_INCREMENT,
  `hora` VARCHAR(50) NULL DEFAULT NULL,
  `idPelicula` INT(11) NULL DEFAULT NULL,
  `idSala` INT(11) NULL DEFAULT NULL,
  `precioTotal` INT(11) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idCartelera`),
  INDEX `FK_cartelera_sala` (`idSala` ASC) VISIBLE,
  INDEX `FK_cartelera_peliculas` (`idPelicula` ASC) VISIBLE,
  CONSTRAINT `FK_cartelera_peliculas`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `cinemar`.`peliculas` (`idPeliculas`),
  CONSTRAINT `FK_cartelera_sala`
    FOREIGN KEY (`idSala`)
    REFERENCES `cinemar`.`sala` (`idSala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`estado` (
  `idEstado` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`tipo_pago` (
  `id_tipoPago` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoPago` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipoPago`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`rol_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`rol_usuarios` (
  `id_rol_usuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol_usuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `dni` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `idRol` INT(11) NULL DEFAULT 2,
  `esFrecuente` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  INDEX `FK__rol_usuarios` (`idRol` ASC) VISIBLE,
  CONSTRAINT `FK__rol_usuarios`
    FOREIGN KEY (`idRol`)
    REFERENCES `cinemar`.`rol_usuarios` (`id_rol_usuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`reserva` (
  `idReserva` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NOT NULL,
  `idEstado` INT(11) NOT NULL,
  `idTipoPago` INT(11) NOT NULL,
  `idCartelera` INT(11) NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `FK_reserva_usuario` (`idUsuario` ASC) VISIBLE,
  INDEX `FK_reserva_estado` (`idEstado` ASC) VISIBLE,
  INDEX `FK_reserva_tipopago` (`idTipoPago` ASC) VISIBLE,
  INDEX `FK_reserva_cartelera` (`idCartelera` ASC) VISIBLE,
  CONSTRAINT `FK_reserva_cartelera`
    FOREIGN KEY (`idCartelera`)
    REFERENCES `cinemar`.`cartelera` (`idCartelera`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_reserva_estado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `cinemar`.`estado` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_reserva_tipopago`
    FOREIGN KEY (`idTipoPago`)
    REFERENCES `cinemar`.`tipo_pago` (`id_tipoPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_reserva_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cinemar`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cinemar`.`reserva_butacas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemar`.`reserva_butacas` (
  `idButaca` INT(11) NOT NULL,
  `idReserva` INT(11) NOT NULL,
  PRIMARY KEY (`idButaca`, `idReserva`),
  INDEX `FK__reserva` (`idReserva` ASC) VISIBLE,
  CONSTRAINT `FK__butacas`
    FOREIGN KEY (`idButaca`)
    REFERENCES `cinemar`.`butacas` (`idButacas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK__reserva`
    FOREIGN KEY (`idReserva`)
    REFERENCES `cinemar`.`reserva` (`idReserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
